#!/usr/bin/env bash
mindepth=0
maxdepth=1

. utils/parse_options.sh

if [ $# -gt 1 ]; then
    echo "Usage: $0 --mindepth 0 --maxdepth 1 [exp]" 1>&2
    echo ""
    echo "Show the system environments and the evaluation results in Markdown format."
    echo 'The default of <exp> is "exp/".'
    exit 1
fi

set -euo pipefail
if [ $# -eq 1 ]; then
    exp=$1
else
    exp=exp
fi


cat << EOF
<!-- Generated by $0 -->
# RESULTS
## Environments
- date: \`$(LC_ALL=C date)\`
EOF


cat << EOF
- Git hash: \`$(git rev-parse HEAD)\`
  - Commit date: \`$(git log -1 --format='%cd')\`

EOF
while IFS= read -r expdir; do
    if ls "${expdir}"/*/*/score_*/result.txt &> /dev/null; then
        echo "## $(basename ${expdir})"



             grep -H -e Sum "${expdir}"/*/*/score_wer/result.txt | grep -v Avg \
                	| sed -e "s#${expdir}/\([^/]*/[^/]*\)/score_wer/result.txt:#|\1#g" \
                	| sed -e 's#Sum##g' | tr '|' ' ' | tr -s ' ' '|' \
|awk -F "|" '{print $2,$9/$4}'

	echo ""

    fi


done < <(find ${exp} -mindepth ${mindepth} -maxdepth ${maxdepth} -type d)
exit 0
while IFS= read -r expdir; do
    if ls "${expdir}"/*/*/score_*/result.txt &> /dev/null; then
        echo "## $(basename ${expdir})"

                	cat << EOF
### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
EOF

             grep -H -e Sum "${expdir}"/*/*/score_wer/result.txt | grep -v Avg \
                	| sed -e "s#${expdir}/\([^/]*/[^/]*\)/score_wer/result.txt:#|\1#g" \
                	| sed -e 's#Sum##g' | tr '|' ' ' | tr -s ' ' '|' \
|awk -F "|" '{print $2"|"$3"|"$4"|"$5/$4"|"$6/$4"|"$7/$4"|"$8/$4"|"$9/$4"|"$10/$3}'



    fi


done < <(find ${exp} -mindepth ${mindepth} -maxdepth ${maxdepth} -type d)
